### ISSUE TITLE
[feat] - @tanstack-query 설정

### ISSUE THREAD

**Issue by developeryeon** [Help-Us/cookhub#10]
📕 Issue Feature 
> 작업의 주제, 제목을 입력하세요 (ex. 레이아웃 UI 구현)
@tanstack-query 설정

🧾Todo
> 수행해야 하는 or 수행한 작업 목록을 입력하세요
- [x] pull 받기

**Comment by G-NooN** [comment]
Pull Request 해서 dev로 합치기 전까지는 issue open 상태로 유지하면 돼요~~
close 하는 기준은 "로컬에서 작업 완료했다"는 뜻보다는 "이 issue를 dev로 push해서 합쳤다"는 뜻이 더 맞습니당~
